# Generated by Django 3.1.7 on 2021-04-21 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pos.models.order
import pos.models.order_item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(blank=True, default=pos.models.order.get_current_time)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_choice', models.PositiveIntegerField(blank=True, choices=[(0, 'NO DISCOUNT'), (10, 'PROMO 10'), (15, 'PROMO 15'), (20, 'FAVORITE CLIENT'), (25, 'PERSONAL')], default=0, verbose_name='Discount')),
                ('order_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(blank=True, default=pos.models.order_item.get_current_time)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Product amount')),
                ('order_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Position cost')),
                ('is_ready', models.BooleanField(blank=True, default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='pos.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.table'),
        ),
    ]
